const text = `"Something strange is going on here. Americans seem to be using two moral compasses. One directs our behavior when it comes to things like sex, family, drugs, and traditional forms of crime. A second provides us ethical guidance in the realm of career, money, and success" (14)
This is a really interesting take. I don't agree that we actually have two moral compasses. When you are so cynical to believe that since "everyone else is doing it", you "might as well do it as well", you don't really have a moral compass. You are only guided by getting as much benefit as possible. So, I think, really, our moral compass is limited, and we only use it on issues that are universally agreed upon as bad, rather than any gray areas, such as piracy: why should you care if the companies are losing profits? It's not like they care about you.

"What happens when you think the system is stacked against people like you and you stop believing that the rules are fair?" (23)
I can relate to this a lot. When you are frustrated about something not being fair, for example when playing a game, it's a lot easier to justify cheating. However, this leads to a breakdown in society. As soon as you start assuming that others are not playing by the rules, and are out to take advantage of you, you stop communicating with them. You start isolating yourself from the people you perceive are cheating, and, overall, this means there is less trust and the society and community suffers.

"You realize that headquarters is expecting everyone to work harder for the same amount of money. Management also makes it clear that anyone who doesn't meet the quotas may be fired. The scant good news in all of this is that if you work really hard, a special incentive in the new system will allow you to make more money than you did before" (29)
The author is really good at creating relatable hypothetical scenarios. By working through the scenario through the lens of the affected person, they come to a natural decision that readers can also empathize with. Here, no car mechanic wants to lie and push for unnecessary changes, but the corner-cutting of corporations has forced them to do this, because their livelihood depends on it. Cheating happens best when it's opaque – the corporations don't know their mechanics are doing this, and most car owners aren't smart enough to realize.

"One day, not too long after you start practicing law, … you just won't have much to show for your efforts in terms of billable hours. … So what you'll do is pad your time sheet just a bit… and before long, you will be stealing from your clients almost every day, and you won't even notice it." (39)
I can understand this sequence of events very well. I think, in general, people can get normalized to something very fast. By that, I mean, they can build habits really quickly, especially if they are bad habits. Bad habits are so prevalent specifically because it is so easy to create them – the correct way to do something is often hard, and has a lot of barriers. So, psychologically, you would go for the easiest path. And, I think this applies to cheating as well. People can lose their integrity so quickly, without even realizing it, because, like bad habits, it benefits them a lot, and they are rarely punished.

"The managers of these large funds were under constant pressure to show results from their stock picks and they leaned on corporate leaders to boost profits – over a period not of many years, but of every quarter." (45)
It's the second time that the author has blamed the current cheating culture on the stock market. And it's an interesting theory: as people start to gravitate towards short term gains, corporations – that used to actually be very ethical – were forced to focus on the bottom-line: cutting corners where possible to maximize shareholder values, and provide the most quarterly earnings rather than setting themselves up for slower, long-term growth.

"While it was Parke-Davis that conceived this troubling marketing effort and put up the money, its ultimate success hinged on the complicity of doctors – many of whom willingly turned their patients into human guinea pigs and lied to their colleagues in order to make an easy buck" (55)
This reminded me of a situation in which the popular doctor and YouTuber Dr. Mike was invited to host a show on TV. This would have been really good for him, he would be able to spread his message about health awareness to a broader audience as well as get more money for it. However, he rejected the offer once realizing that he would be required to promote certain medical products that the TV show would give him. And since he couldn't check the effectiveness or the safety of the product, he would essentially be lying to his audience. Unfortunately, not all doctors have as much integrity as Dr. Mike, but it is a hopeful anecdote that not all doctors are bent on making profit.

"We never reckoned with how 'mean' would affect the quality of life and ethics of professionals or with the unseemly pressures that would be exerted by 'lean'" (62)
This is an unique sentence structure – it breaks down the common phrase "lean and mean" into its two components: "lean", meaning cutting any excess, and "mean", meaning focused on a specific objective. And by being able to connect both of those two words to the actual situation they are being used to describe, "lean": workers are seeing their salaries cut, and "mean": workers are doing everything they can to get to their objective of obtaining more money, readers are convinced that "lean and mean" is an apt description of the cheating culture.

"Ken Caminiti was a third baseman for the San Diego Padres when he began taking banned steroids in 1996 to help overcome an injury. Caminiti did more than just heal. He played as never before – with 40 home runs, 130 RBIs, and a .326 batting average. 'At first I felt like a cheater,' Caminiti told Sports Illustrated. 'But I looked around, and everybody was doing it.'" (75)
This passage is really representative of the whole message of the book. First, the author builds a lot of logos. He uses a variety of numbers to help support his point, as well as putting his claims into perspective. Second, Callahan directly quotes Caminiti saying "everyone was doing it", which is exactly one of the claims that Callahan repeatedly makes: people normalize cheating because they see everyone else is doing it.

"Yet in the real world, big pay gaps can have a corrosive effect on the integrity of even those people who should be extremely grateful for all the money they are earning." (89)
It's an interesting perspective to consider: people are unhappy even though they have a great quality of life. They still want more (and therefore cheat to do so), because they are comparing themselves to the people that are even more successful than them. If you had a salary of $110,000, but you worked around people that made $200,000, you would be unhappy, even though you have a great salary. And that is a much harder psychological problem to solve than just blaming the stock market forcing people to optimize for the bottom line.

"WorldCom's meltdown dwarfed Enron's in nearly every way. The frauds were much larger, many more people lost their jobs, and the loss to investors was also greater. Over $175 billion in equity value, three times what was lost in the Enron bankruptcy, disappeared as WorldCom disintegrated." (103)
The author assumes that the readers know what Enron was. Enron was an electricity, natural gas, communications, and pulp and paper company. By the end of 2001, it was revealed that it had been involved in accounting fraud and systemic corruption. So, the author assumes that the reader has some basic knowledge of the history of companies during 2001, to be able to truly understand and compare the magnitudes of the frauds that were happening.

"As making money moved front and center, young people stopped caring about other things. In the late 1960s, believe it or not, the most important goal of college freshman was 'developing a meaningful philosophy of life,' cited by over 80 percent of entering students. The centrality of this goal waned steadily over the next twenty years, reaching an all-time low of 39 percent in 1987, at the height of the '80s boom." (116)
The author has tried to explain how individualism has led to the hippie culture which promoted the freedom of expression and choice, which then got corrupted into laissez-faire economics and having a free, unfettered market. The author backs up all these claims in his historical narrative with statistics from polls, and he relies heavily on logos to get his point across. Here, Callahan uses polling data to argue that college students reflect the changing culture, and they have lost their desire for critical thinking, and instead see college as a way to advance their own career goals.

"At the same time, our lack of sympathy for life's losers makes us less prone to outrage when ordinary people are exploited by powerful cheaters. We are as likely to blame the victim as the villain. For example, in the aftermath of corporate scandals, a member of commentators pooh-poohed the losses of those who invested in Enron …'They failed to follow the common sense rules of asset diversification'" (126)
Since it is believed that America is an "even playing field" and the only way to get rich is through hard work, the wealthy become admired for their moral righteousness. This is a really interesting perspective on how we view class society, and it is a good explanation of the callousness towards the poor that many people have. Why help them if they are "lazy" and "brought it on themselves"? Unfortunately, it seems that America still believes in the "even playing field" even though it doesn't exist anymore, and that more people are cheating to get to the top instead.

"In June 2003, six former Xerox executives settled with the SEC, agreeing to pay $22 million but – you guessed it – admitting to no wrongdoing" (144)
The author keeps on mentioning these scandals, but most importantly, "admitting to no wrongdoing". Unfortunately, it seems that while the companies are being punished, the punishments are still quite small – they aren't so public as to damage the company's reputation. They just have to pay a small fine quietly, and don't have to announce that they did anything wrong. And without that kind of accountability, getting caught for cheating has less of a consequence.

"'When there are ten thousand documents, some of which are bank statements containing thousands of transactions, and the opposition argues the significance of every single item, the process becomes extraordinarily difficult.' In the face of battles like these, it simply makes more sense for the IRS to concentrate its enforcement efforts on vulnerable targets." (158)
This unfortunately connects very well to the winner-takes-all society that Callahan describes. The winners are able to get away with all their cheating simply because they have more resources, and more knowledge of how to get away with cheating. They are able to simply make the process so complicated that the IRS has no choice but to give up. Wealth definitely buys political power, and when the IRS loses its budget because of the political power of the wealthy, it has no choice but to concede even more to the wealthy, leading to a negative cycle. And, in the end, the poor pay for it.

 "Writing in the mid-twentieth century, the sociologist Robert Merton observed that Americans are taught that everyone can succeed if they work hard enough. America was a 'society which places a high premium on economic affluence and social ascent for all its members.' But Merton also pointed out that there is no 'corresponding emphasis upon the legitimate avenues on which to march toward this goal.' Americans worshipped financial success without being too concerned about how people got ahead … These pressures were especially poisonous, Merton said, in a nation where not everyone actually could succeed – where there were limits on the economic opportunities that were available" (173)
This is both a very interesting perspective and it also adds to the author's credibility. First, it adds to the author's credibility because this passage was written in the mid-twentieth century. The cheating that the author has been writing about has had its roots in American history for a long time. Second, it's a very interesting perspective because America is unique in that it very much emphasizes the freedom of economic opportunity and mobility. So, when people are literally taught by their culture that they are expected to be able to move upward on the social ladder, it's easy to forget that they don't place as much importance on moving upwards legitimately.

"Exacting revenge against tyrannical cable companies strikes many Americans as a just cause if ever there was one. Those engaged in cable theft regularly cite the misdeeds of cable companies to justify their behavior. A favorite excuse uses the logic of expropriation – that the cable companies are making so much money by gouging consumers that they should be forced to pay some back." (190)
This is a very common excuse on why people pirate – they feel like they are morally justified in doing so. I personally understand the excuse because I use it as well when I pirate things. These are huge corporations, and they don't care about their customers, and I wasn't going to be a customer anyways, so why should it matter? What I didn't realize was that at the end of the day, no matter how "righteous" it seems, you are not participating in social activism. You are still stealing, and corporations become more greedy because of those lost profits, leading to a negative cycle.
"It was considered the civic duty of morning students to fully brief afternoon students on the content – and answers – of tests in a given class. Students who were savvy, and unscrupulous, were wise to take courses in their weaker subjects in afternoon slots." (202)
In all honesty, I've never cheated in a class before, so when the author wrote about all of these top high schools having widespread cheating, I couldn't relate to it very much. I've never really heard stories from my friends about anyone cheating, much less getting caught. But maybe that's just because of the environment I grew up in, where thankfully, it isn't so cutthroat, and there are many opportunities to succeed. However, this one passage, about earlier classes sharing the test to later classes is something I've heard a lot about. And I never really considered it "cheating" because, for me, cheating on a test feels more like something you have to be sneaky about, and hide from the teacher. So, it's interesting that in this book, a lot of things I don't really consider "cheating", are technically cheating.

"The American résumé, in fact, is right up there with lawyers' timesheets and corporate earnings statements as among the most misleading documents around." (220)
In a book about cheating, it's hard to find any real continuity. You can talk about where cheating happens, such as with lawyers, with doctors, with corporations, or you can talk about the history of cheating. In this book, Callahan organizes cheating into categories, from the upper class, to the current chapter, cheating at school even before entering the job market. So, to connect back to previous ideas, Callahan makes references, such as "lawyers' timesheets" – referring back to when lawyers would inflate their timesheets to ridiculous amounts to keep up with quota and billable hours, and "corporate earnings" – the history of Enron.

"“It doesn’t do a lot for the depositors’ confidence when they read in the newspaper that their bank just nabbed a crooked loan officer, " said Wells."As a result many businesses simply fire dishonest employees, who then are unwittingly hired by other companies.”" (238)
This is a common structure that the author uses throughout the book. First, he talks about a problem related to cheating, whether that be of lawyers, of students, or of athletes. Then, he talks about how the high stakes of American society has forced these people to cheat, because it's the only way to keep up. He includes quotes from other people to support his claim that cheating is widespread and is a big problem. It's a good strategy because talking about cheating is hard because there are so many ways to cheat. So, in order for this book to have the broadest reach possible, he needs to include a lot of examples of cheating.

"Then again, maybe those humid summers are too much for you, in which case you'll be wise to consider the minimum-security camp in Lompoc, California, where Ivan Boesky did his soft time, as did the Watergate offenders." (249)
This passage is especially powerful comparing the punishment dealt to street crimes, as compared to "white-collar" criminals. First, the author built up pathos by talking about how unfairly long punishments were doled out to what were essentially troubled youths caught at the wrong place at the wrong time. Then, he goes on to switch to second person, talking to the readers themselves about how white-collar criminals, with their wealth and connections, can essentially see prisons as a sort of "college", and it's certainly compared that way, because, since they haven't committed any violent crimes, they can go to minimum-security prisons which are nicer. So no matter what, their punishment is at most a mild inconvenience for them.

"'These steps should appeal to both sides of the American character: each asks a lot of people, as the Tough American demands; yet each holds out real rewards, as the Fair American suggests. And all four envision the government not as the sole solution to our problems, but as a catalyst for action that leverages its resources in partnership with the private and nonprofit sectors." (268)
By recognizing that the American ethos is made up of both a "tough american" who expects people to work hard and to "toughen up", as well as a "fair american" who believes that everyone deserves an opportunity to succeed, Callahan is able to build ethos as he demonstrates he understands the cheating problem well, and so his suggestions for how to fix the situation is more credible, and more in-line with reality.

"The grotesque materialism of U.S. society is not only bad because it makes people look endlessly inward, creating competitive anxieties about status, looks, and class position. It is not only bad because it has created intense spending pressures on people at a time when many households have been running in place economically. Nor is it only bad because of its destructive environmental consequences. Excessive personal consumption is also bad because it drains national resources away from more important spending that could strengthen our communities and elevate our quality of life." (278)
By using repetition, "not only bad because … , it is not only bad because … nor is it only bad because …", Callahan is really able to drive home the point that excessive spending is bad. Materialism has so many consequences, from creating anxiety and pressure, as well as draining resources that could have been used more productively. This repetition structure strengthens the argument, because all of these reasons are powerful and valid, and listing them all together really emphasizes to the reader that materialism culture is a huge problem in America.

"For what it's worth, my advice to those who cheat or are around cheating boils down to two simple ideas: one, go ahead and be a chump; and two, don't hesitate to be a pain in the ass." (293)
This is very difficult advice to follow, because personally, I have the experience that it is better to go out of the way, to not be a hassle, to not be the "odd one out", and to not take up other peoples' time. And I think a majority of Americans share this opinion. To be fair, it's a lot easier to "go with the flow" and do what's natural. It's much harder to take a stance, and to take up other peoples' time and fight for your beliefs. It's necessary, but it's hard.

"I have met many other ethics entrepreneurs beyond these, and I find their efforts not just impressive, but reassuring. The cheating culture is being contested every day, with growing zeal and creativity." (307)
In the main book, it is mostly an outline of "current events" of 2004. It offers solutions, but doesn't end hopefully, instead, giving readers a choice to change for the better. However, this afterword helps to end the book on a true positive note. Callahan mentions several events that have occurred after the publishing of the book, that include court trials for people that, at the time of the book, were still walking free. The afterword encourages readers to continue being virtuous, and continue battling the temptation to cheat, because their efforts are paying off.

`;

const lines = text.trim().split(/\n{2,}/);

const bubs = lines.map(k => {
    const [quote, text] = k.split("\n");
    const pageNumber = +/\((\d+)\)/g.exec(quote)[1];

    return `---
title: 
order: ${pageNumber}
---

> ${quote}

${text}`;
});

const fs = require("fs");
for (let i = 0; i < bubs.length; i++) {
    fs.writeFileSync(`output_folder/blog-page-${i + 1}.md`, bubs[i]);
}